[project]
name = "china-weather-mcp-server"
version = "1.0"
description = "MCP server to query weather in Chinese cities"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
]
